// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpzbSysREshVOgyLKtxqdGR-tOdPPEdoc',
    appId: '1:771187568007:web:daaf3e3ebb958c0d59f722',
    messagingSenderId: '771187568007',
    projectId: 'project-ffku-2deb4',
    authDomain: 'project-ffku-2deb4.firebaseapp.com',
    storageBucket: 'project-ffku-2deb4.appspot.com',
    measurementId: 'G-1SKK0D6VN5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBq2YL1x_tSdIsAV26hDueRLw02-l3uBIo',
    appId: '1:771187568007:android:4a66ecf274db714c59f722',
    messagingSenderId: '771187568007',
    projectId: 'project-ffku-2deb4',
    storageBucket: 'project-ffku-2deb4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2_A9P7gfbB483dTC9rifncJRf7E2WI40',
    appId: '1:771187568007:ios:8dfde1d534e7760159f722',
    messagingSenderId: '771187568007',
    projectId: 'project-ffku-2deb4',
    storageBucket: 'project-ffku-2deb4.appspot.com',
    iosBundleId: 'com.example.deteksibuah',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2_A9P7gfbB483dTC9rifncJRf7E2WI40',
    appId: '1:771187568007:ios:8dfde1d534e7760159f722',
    messagingSenderId: '771187568007',
    projectId: 'project-ffku-2deb4',
    storageBucket: 'project-ffku-2deb4.appspot.com',
    iosBundleId: 'com.example.deteksibuah',
  );
}
